apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labled:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      secretRef: 