apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo-deploy
  namespace: default
  labels:
    app: secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  volumes:
  - name: secret-volume
    secret:
      secretName: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", 'sleep 600']
        volumeMounts:
        - name: secret-volume
          mountPath: /mydata
