apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: default
spec:
  activeDeadlineSeconds: 10
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "60"]
      restartPolicy: Never