apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["echo", "Hello kubernetes !"]
      restartPolicy: Never
  backoffLimit: 4