apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1

  template:
    metadata:
      labels:
        app: nginx
    
    spec:
      volumes:
      - name: shared-volume
        emptyDir: {}

      initContainers:
      - name: web-content-creator
        image: busybox
        volumeMounts:
        - name: shared-volume
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h1>Hello Hello kubernetes from initContainer</h1>" > /webdata/index.html']

      - name: web-content-creator-2
        image: busybox
        volumeMounts:
        - name: shared-volume
          mountPath: "/webdata"
        command: ["/bin/sh", "-c", 'echo "<h2 style='color:red'>Hello kubernetes from initContainer</h2>" > /webdata/red.html']
      # restartPolicy: Never
      
      containers:
      - name: nginx
        image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
        volumeMounts:
        - name: shared-volume
          mountPath: "/usr/share/nginx/html"
        ports:
        - containerPort: 80
